# .swiftlint.yml
disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - line_length
  - force_cast

opt_in_rules: # rules to explicitly enable
  - empty_count
  - implicitly_unwrapped_optional

included: # paths to include during linting
  - CalculatorApp

excluded: # paths to ignore during linting
  - Pods
  - Carthage

line_length:
  warning: 120
  error: 200

type_body_length:
  warning: 200
  error: 300

